create table cart_item(
    id bigint generated by default as identity,
    cart_id bigint,
    product_id bigint,
    quantity int not null,
    PRIMARY KEY(id),
    CONSTRAINT fk_cart
    FOREIGN KEY(cart_id)
        REFERENCES cart(cart_id),
    CONSTRAINT fk_product
        FOREIGN KEY(product_id)
            REFERENCES products(id)

)